name: core
description: core plagain for flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter_bloc: any
  freezed_annotation: ^2.1.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  retrofit: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.2.0 
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  integration_test: ^0.8.1
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3
